# Generated by Django 4.0.4 on 2023-08-28 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fertilisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etape', models.CharField(max_length=200)),
                ('periode_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('periode_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('action_sur_terre', models.CharField(choices=[('labourage', 'Labourage'), ('ameublissement', 'Ameublissement'), ('bbbbbb', 'bbbbbbb')], max_length=20)),
                ('irrigation_quantite', models.FloatField(blank=True, null=True)),
                ('irrigation_periode', models.CharField(blank=True, max_length=200, null=True)),
                ('type_fertilisation_quantite', models.FloatField(blank=True, null=True)),
                ('type_fertilisation_periode', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='etapes/%y/%m/%d')),
                ('type_fertilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fertilisation.fertilisation')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fertilisation.modéle_variante')),
            ],
        ),
    ]
